### ISSUE TITLE
Component Editor has 3 Options that no longer serve any purpose

### ISSUE THREAD

**Issue by lhengen** [TurboPack/Essentials#2]
I you Right click an instance of a TesRollUp component for example, the first 3 local menu options are:

TurboPower on the Web
Essentials Home Page
Send a Support Message

The first two invoke a webbrowser to a non-existant URL.  The second I assume would launch the default mail client with a mailTo link.

Where is there documentation on the components?  Even the original TurboPower documentation would be useful especially for developers not familiar with the suite.  Even a component list with Screenshots would be useful when you're looking for a component with certain UI presentation and behaviour, since there are no Demo projects.

**Comment by romankassebaum** [comment]
I have no documentation. This library should only be used for legacy code in existing projects. Don't use these components in new projects.
