### ISSUE TITLE
I cannot figure out how to get the data aware edit controls to show up in design time.

### ISSUE THREAD

**Issue by Bestware1** [TurboPack/Essentials#3]
I installed from the GetIt Package Manager in Delphi 11 (Alexandria).  The data aware controls do not get installed.  I have an old code base that I need to bring into Delphi and it flags errors for controls like TEsDBNumberEdit  and TEsDBDateEdit.  The code appears to be available in the source units EsDbEd.pas but they are not installed in the design time package Essentials1.  Looking for any advice about how to get these controls installed in the design time package.

**Comment by romankassebaum** [comment]
There was no designtime package for the data aware controls. I just added it.

**Comment by Bestware1** [comment]
Thank you!  I tried installing from the GitIt Package Manager in Delphi 11, but it still installed the older versions.  I don't know if it takes awhile or if something needs to be updated somewhere else to make that work.  I was able to download the Zip file from here and manually build and install the packages EssentialsDD.dpk and EssentialsDBDD.dpk .  Now my older project loads and compiles fine, so thank you for helping fix this.  It could help others if the package descriptions on the web page would list these packages as the two Design Time packages that need to be built and installed if installing manually.

**Comment by romankassebaum** [comment]
I asked Embarcadero to update GetIt. I cannot do it myself.

**Comment by romankassebaum** [comment]
The description is updated.

**Comment by Bestware1** [comment]
Perfect!  Thank you very much.
